export default {
    matchFeature: {
        "awayTeamId": 0,
        "awayTeamShortName": "阿马多拉",
        "eachHomeAway": {
            "awayDrawMatchCnt": 3,
            "awayLossGoalMatchCnt": 4,
            "awayScoreRatio": "40",
            "awayWinGoalMatchCnt": 3,
            "homeDrawMatchCnt": 1,
            "homeLossGoalMatchCnt": 1,
            "homeScoreRatio": "83",
            "homeWinGoalMatchCnt": 8,
            "totalLegCnt": 10
        },
        "eachSameHomeAway": {
            "awayDrawMatchCnt": 4,
            "awayLossGoalMatchCnt": 4,
            "awayScoreRatio": "33",
            "awayWinGoalMatchCnt": 2,
            "homeDrawMatchCnt": 1,
            "homeLossGoalMatchCnt": 1,
            "homeScoreRatio": "83",
            "homeWinGoalMatchCnt": 8,
            "totalLegCnt": 10
        },
        "goalAvg": {
            "awayGoalAvgCnt": "1.6",
            "awayGoalAvgCntRatio": "47.1",
            "homeGoalAvgCnt": "1.8",
            "homeGoalAvgCntRatio": "52.9",
            "totalLegCnt": 10
        },
        "homeTeamId": 0,
        "homeTeamShortName": "波尔图",
        "last": {
            "awayDrawMatchCnt": 1,
            "awayLossGoalMatchCnt": 3,
            "awayScoreRatio": "27",
            "awayWinGoalMatchCnt": 1,
            "homeDrawMatchCnt": 1,
            "homeLossGoalMatchCnt": 1,
            "homeScoreRatio": "67",
            "homeWinGoalMatchCnt": 3,
            "totalLegCnt": 5
        },
        "lossGoalAvg": {
            "awayLossGoalAvgCnt": "1.8",
            "awayLossGoalAvgCntRatio": "72.0",
            "homeLossGoalAvgCnt": "0.7",
            "homeLossGoalAvgCntRatio": "28.0",
            "totalLegCnt": 10
        },
        "matchId": 2367538,
        "sameHomeAway": {
            "awayDrawMatchCnt": 1,
            "awayLossGoalMatchCnt": 2,
            "awayScoreRatio": "11",
            "awayWinGoalMatchCnt": 0,
            "homeDrawMatchCnt": 1,
            "homeLossGoalMatchCnt": 0,
            "homeScoreRatio": "78",
            "homeWinGoalMatchCnt": 2,
            "totalLegCnt": 3
        },
        "sportteryAwayTeamId": 261,
        "sportteryHomeTeamId": 937,
        "sportteryMatchId": 2036064,
        "uniformAwayTeamId": 35076,
        "uniformHomeTeamId": 141
    },
    matchHeadData: {
        "awayTeamId": 51318,
        "awayTeamLogoPath": "//static.sporttery.cn/res_1_0/jcw/upload/mnjc/zq/1/261.png",
        "awayTeamShortName": "阿马多拉",
        "fullCourtGoal": "3:1",
        "gameweek": "14",
        "groupId": 0,
        "groupName": "",
        "homeTeamId": 1678,
        "homeTeamLogoPath": "//static.sporttery.cn/res_1_0/jcw/upload/mnjc/zq/1/937.png",
        "homeTeamShortName": "波尔图",
        "matchDateTime": "2025-12-16 04:45",
        "matchId": 2367538,
        "matchNum": "周一006",
        "phaseId": 47981,
        "phaseName": "Regular Season",
        "seasonId": 13480,
        "seasonName": "2025/2026",
        "sportteryAwayTeamId": 261,
        "sportteryHomeTeamId": 937,
        "sportteryMatchId": 2036064,
        "sportteryTournamentId": 55,
        "tournamentCnName": "葡萄牙超级联赛",
        "tournamentCnShortName": "葡超",
        "tournamentId": 140,
        "uniformAwayTeamId": 35076,
        "uniformHomeTeamId": 141,
        "uniformLeagueId": 78,
        "uniformMatchId": 2334340,
        "wbsjStats": {
            "away": {
                "groupName": "",
                "phaseName": "Regular Season",
                "ranking": "14",
                "sAwayDrawMatchCnt": "3",
                "sAwayLossGoalMatchCnt": "3",
                "sAwayWinGoalMatchCnt": "1",
                "sDrawMatchCnt": "5",
                "sLossGoalMatchCnt": "6",
                "sWinGoalMatchCnt": "3",
                "seasonName": "2025/2026"
            },
            "home": {
                "groupName": "",
                "phaseName": "Regular Season",
                "ranking": "1",
                "sDrawMatchCnt": "1",
                "sHomeDrawMatchCnt": "1",
                "sHomeLossGoalMatchCnt": "0",
                "sHomeWinGoalMatchCnt": "6",
                "sLossGoalMatchCnt": "0",
                "sWinGoalMatchCnt": "13",
                "seasonName": "2025/2026"
            }
        }
    },
    matchHistory: {
        "matchList": [
            {
                "awayTeamFullCourtGoalCnt": "0",
                "awayTeamId": 1678,
                "awayTeamShortName": "波尔图",
                "fullCourtGoal": "2:0",
                "gmLeagueId": 0,
                "halfTimeGoal": "1:0",
                "homeMatchResult": "away",
                "homeTeamFullCourtGoalCnt": "2",
                "homeTeamId": 51318,
                "homeTeamShortName": "阿马多拉",
                "matchDate": "2025-04-27",
                "matchId": 2146932,
                "seasonId": 11974,
                "sportteryAwayTeamId": 937,
                "sportteryHomeTeamId": 261,
                "sportteryMatchId": 0,
                "sportteryTournamentId": 0,
                "teamMatchResult": "",
                "totalTeamFullCourtGoalCnt": 2,
                "tournamentId": 140,
                "tournamentShortName": "葡超",
                "uniformAwayTeamId": 141,
                "uniformHomeTeamId": 35076,
                "uniformLeagueId": 78,
                "winningTeam": "home"
            },
            {
                "awayTeamFullCourtGoalCnt": "0",
                "awayTeamId": 51318,
                "awayTeamShortName": "阿马多拉",
                "fullCourtGoal": "2:0",
                "gmLeagueId": 55,
                "halfTimeGoal": "1:0",
                "homeMatchResult": "home",
                "homeTeamFullCourtGoalCnt": "2",
                "homeTeamId": 1678,
                "homeTeamShortName": "波尔图",
                "matchDate": "2024-12-17",
                "matchId": 2147084,
                "seasonId": 11974,
                "sportteryAwayTeamId": 261,
                "sportteryHomeTeamId": 937,
                "sportteryMatchId": 1028773,
                "sportteryTournamentId": 55,
                "teamMatchResult": "",
                "totalTeamFullCourtGoalCnt": 2,
                "tournamentId": 140,
                "tournamentShortName": "葡超",
                "uniformAwayTeamId": 35076,
                "uniformHomeTeamId": 141,
                "uniformLeagueId": 78,
                "winningTeam": "home"
            },
            {
                "awayTeamFullCourtGoalCnt": "0",
                "awayTeamId": 51318,
                "awayTeamShortName": "阿马多拉",
                "fullCourtGoal": "2:0",
                "gmLeagueId": 0,
                "halfTimeGoal": "1:0",
                "homeMatchResult": "home",
                "homeTeamFullCourtGoalCnt": "2",
                "homeTeamId": 1678,
                "homeTeamShortName": "波尔图",
                "matchDate": "2024-02-18",
                "matchId": 1840485,
                "seasonId": 9666,
                "sportteryAwayTeamId": 261,
                "sportteryHomeTeamId": 937,
                "sportteryMatchId": 0,
                "sportteryTournamentId": 0,
                "teamMatchResult": "",
                "totalTeamFullCourtGoalCnt": 2,
                "tournamentId": 140,
                "tournamentShortName": "葡超",
                "uniformAwayTeamId": 35076,
                "uniformHomeTeamId": 141,
                "uniformLeagueId": 78,
                "winningTeam": "home"
            },
            {
                "awayTeamFullCourtGoalCnt": "1",
                "awayTeamId": 1678,
                "awayTeamShortName": "波尔图",
                "fullCourtGoal": "0:1",
                "gmLeagueId": 0,
                "halfTimeGoal": "0:1",
                "homeMatchResult": "home",
                "homeTeamFullCourtGoalCnt": "0",
                "homeTeamId": 51318,
                "homeTeamShortName": "阿马多拉",
                "matchDate": "2023-09-16",
                "matchId": 1840416,
                "seasonId": 9666,
                "sportteryAwayTeamId": 937,
                "sportteryHomeTeamId": 261,
                "sportteryMatchId": 0,
                "sportteryTournamentId": 0,
                "teamMatchResult": "",
                "totalTeamFullCourtGoalCnt": 1,
                "tournamentId": 140,
                "tournamentShortName": "葡超",
                "uniformAwayTeamId": 141,
                "uniformHomeTeamId": 35076,
                "uniformLeagueId": 78,
                "winningTeam": "away"
            },
            {
                "awayTeamFullCourtGoalCnt": "3",
                "awayTeamId": 51318,
                "awayTeamShortName": "阿马多拉",
                "fullCourtGoal": "3:3",
                "gmLeagueId": 0,
                "halfTimeGoal": "-:-",
                "homeMatchResult": "draw",
                "homeTeamFullCourtGoalCnt": "3",
                "homeTeamId": 1678,
                "homeTeamShortName": "波尔图",
                "matchDate": "2023-07-26",
                "matchId": 1975023,
                "seasonId": 10656,
                "sportteryAwayTeamId": 261,
                "sportteryHomeTeamId": 937,
                "sportteryMatchId": 0,
                "sportteryTournamentId": 0,
                "teamMatchResult": "",
                "totalTeamFullCourtGoalCnt": 6,
                "tournamentId": 1014,
                "tournamentShortName": "俱乐部赛",
                "uniformAwayTeamId": 35076,
                "uniformHomeTeamId": 141,
                "uniformLeagueId": 719,
                "winningTeam": "draw"
            }
        ],
        "statistics": {
            "drawMatchCnt": 1,
            "drawProbability": "20%",
            "goalCnt": 0,
            "lossGoalCnt": 0,
            "lossGoalMatchCnt": 1,
            "lossProbability": "20%",
            "netGoal": 0,
            "sportteryTeamId": 0,
            "teamId": 0,
            "teamShortName": "波尔图",
            "totalLegCnt": 5,
            "winGoalMatchCnt": 3,
            "winProbability": "60%"
        }
    },
    MatchTables: {
        "awayTables": {
            "total": {
                "drawMatchCnt": 5,
                "gmTeamId": 261,
                "goalCnt": 17,
                "groupId": 0,
                "groupName": "",
                "lossGoalCnt": 22,
                "lossGoalMatchCnt": 6,
                "netGoal": -5,
                "phaseName": "Regular Season",
                "points": "14",
                "ranking": "14",
                "teamShortName": "阿马多拉",
                "totalLegCnt": 14,
                "uniformTeamId": 0,
                "wbsjTeamId": 51318,
                "winGoalMatchCnt": 3,
                "winProbability": "21%"
            },
            "away": {
                "drawMatchCnt": 3,
                "gmTeamId": 261,
                "goalCnt": 7,
                "groupId": 0,
                "groupName": "",
                "lossGoalCnt": 13,
                "lossGoalMatchCnt": 3,
                "netGoal": -6,
                "phaseName": "Regular Season",
                "points": "6",
                "ranking": "14",
                "teamShortName": "阿马多拉",
                "totalLegCnt": 7,
                "uniformTeamId": 35076,
                "wbsjTeamId": 51318,
                "winGoalMatchCnt": 1,
                "winProbability": "14%"
            },
            "home": {
                "drawMatchCnt": 2,
                "gmTeamId": 261,
                "goalCnt": 10,
                "groupId": 0,
                "groupName": "",
                "lossGoalCnt": 9,
                "lossGoalMatchCnt": 3,
                "netGoal": 1,
                "phaseName": "Regular Season",
                "points": "8",
                "ranking": "12",
                "teamShortName": "阿马多拉",
                "totalLegCnt": 7,
                "uniformTeamId": 141,
                "wbsjTeamId": 51318,
                "winGoalMatchCnt": 2,
                "winProbability": "29%"
            }
        },
        "gmLeagueId": 55,
        "homeTables": {
            "total": {
                "drawMatchCnt": 1,
                "gmTeamId": 937,
                "goalCnt": 30,
                "groupId": 0,
                "groupName": "",
                "lossGoalCnt": 4,
                "lossGoalMatchCnt": 0,
                "netGoal": 26,
                "phaseName": "Regular Season",
                "points": "40",
                "ranking": "1",
                "teamShortName": "波尔图",
                "totalLegCnt": 14,
                "uniformTeamId": 0,
                "wbsjTeamId": 1678,
                "winGoalMatchCnt": 13,
                "winProbability": "93%"
            },
            "away": {
                "drawMatchCnt": 0,
                "gmTeamId": 937,
                "goalCnt": 16,
                "groupId": 0,
                "groupName": "",
                "lossGoalCnt": 2,
                "lossGoalMatchCnt": 0,
                "netGoal": 14,
                "phaseName": "Regular Season",
                "points": "21",
                "ranking": "1",
                "teamShortName": "波尔图",
                "totalLegCnt": 7,
                "uniformTeamId": 35076,
                "wbsjTeamId": 1678,
                "winGoalMatchCnt": 7,
                "winProbability": "100%"
            },
            "home": {
                "drawMatchCnt": 1,
                "gmTeamId": 937,
                "goalCnt": 14,
                "groupId": 0,
                "groupName": "",
                "lossGoalCnt": 2,
                "lossGoalMatchCnt": 0,
                "netGoal": 12,
                "phaseName": "Regular Season",
                "points": "19",
                "ranking": "1",
                "teamShortName": "波尔图",
                "totalLegCnt": 7,
                "uniformTeamId": 141,
                "wbsjTeamId": 1678,
                "winGoalMatchCnt": 6,
                "winProbability": "86%"
            }
        },
        "leagueShortName": "葡超",
        "phaseId": 47981,
        "seasonId": 13480,
        "seasonName": "2025/2026",
        "tournamentId": 140,
        "uniformLeagueId": 78,
        "uniformMatchId": 2334340
    }
}