export default {
  matchFeature: {
    awayTeamId: 0,
    awayTeamShortName: "阿马多拉",
    eachHomeAway: {
      awayDrawMatchCnt: 3,
      awayLossGoalMatchCnt: 4,
      awayScoreRatio: "40",
      awayWinGoalMatchCnt: 3,
      homeDrawMatchCnt: 1,
      homeLossGoalMatchCnt: 1,
      homeScoreRatio: "83",
      homeWinGoalMatchCnt: 8,
      totalLegCnt: 10,
    },
    eachSameHomeAway: {
      awayDrawMatchCnt: 4,
      awayLossGoalMatchCnt: 4,
      awayScoreRatio: "33",
      awayWinGoalMatchCnt: 2,
      homeDrawMatchCnt: 1,
      homeLossGoalMatchCnt: 1,
      homeScoreRatio: "83",
      homeWinGoalMatchCnt: 8,
      totalLegCnt: 10,
    },
    goalAvg: {
      awayGoalAvgCnt: "1.6",
      awayGoalAvgCntRatio: "47.1",
      homeGoalAvgCnt: "1.8",
      homeGoalAvgCntRatio: "52.9",
      totalLegCnt: 10,
    },
    homeTeamId: 0,
    homeTeamShortName: "波尔图",
    last: {
      awayDrawMatchCnt: 1,
      awayLossGoalMatchCnt: 3,
      awayScoreRatio: "27",
      awayWinGoalMatchCnt: 1,
      homeDrawMatchCnt: 1,
      homeLossGoalMatchCnt: 1,
      homeScoreRatio: "67",
      homeWinGoalMatchCnt: 3,
      totalLegCnt: 5,
    },
    lossGoalAvg: {
      awayLossGoalAvgCnt: "1.8",
      awayLossGoalAvgCntRatio: "72.0",
      homeLossGoalAvgCnt: "0.7",
      homeLossGoalAvgCntRatio: "28.0",
      totalLegCnt: 10,
    },
    matchId: 2367538,
    sameHomeAway: {
      awayDrawMatchCnt: 1,
      awayLossGoalMatchCnt: 2,
      awayScoreRatio: "11",
      awayWinGoalMatchCnt: 0,
      homeDrawMatchCnt: 1,
      homeLossGoalMatchCnt: 0,
      homeScoreRatio: "78",
      homeWinGoalMatchCnt: 2,
      totalLegCnt: 3,
    },
    sportteryAwayTeamId: 261,
    sportteryHomeTeamId: 937,
    sportteryMatchId: 2036064,
    uniformAwayTeamId: 35076,
    uniformHomeTeamId: 141,
  },
  matchHeadData: {
    awayTeamId: 51318,
    awayTeamLogoPath: "//static.sporttery.cn/res_1_0/jcw/upload/mnjc/zq/1/261.png",
    awayTeamShortName: "阿马多拉",
    fullCourtGoal: "3:1",
    gameweek: "14",
    groupId: 0,
    groupName: "",
    homeTeamId: 1678,
    homeTeamLogoPath: "//static.sporttery.cn/res_1_0/jcw/upload/mnjc/zq/1/937.png",
    homeTeamShortName: "波尔图",
    matchDateTime: "2025-12-16 04:45",
    matchId: 2367538,
    matchNum: "周一006",
    phaseId: 47981,
    phaseName: "Regular Season",
    seasonId: 13480,
    seasonName: "2025/2026",
    sportteryAwayTeamId: 261,
    sportteryHomeTeamId: 937,
    sportteryMatchId: 2036064,
    sportteryTournamentId: 55,
    tournamentCnName: "葡萄牙超级联赛",
    tournamentCnShortName: "葡超",
    tournamentId: 140,
    uniformAwayTeamId: 35076,
    uniformHomeTeamId: 141,
    uniformLeagueId: 78,
    uniformMatchId: 2334340,
    wbsjStats: {
      away: {
        groupName: "",
        phaseName: "Regular Season",
        ranking: "14",
        sAwayDrawMatchCnt: "3",
        sAwayLossGoalMatchCnt: "3",
        sAwayWinGoalMatchCnt: "1",
        sDrawMatchCnt: "5",
        sLossGoalMatchCnt: "6",
        sWinGoalMatchCnt: "3",
        seasonName: "2025/2026",
      },
      home: {
        groupName: "",
        phaseName: "Regular Season",
        ranking: "1",
        sDrawMatchCnt: "1",
        sHomeDrawMatchCnt: "1",
        sHomeLossGoalMatchCnt: "0",
        sHomeWinGoalMatchCnt: "6",
        sLossGoalMatchCnt: "0",
        sWinGoalMatchCnt: "13",
        seasonName: "2025/2026",
      },
    },
  },
  matchHistory: {
    matchList: [
      {
        awayTeamFullCourtGoalCnt: "0",
        awayTeamId: 1678,
        awayTeamShortName: "波尔图",
        fullCourtGoal: "2:0",
        gmLeagueId: 0,
        halfTimeGoal: "1:0",
        homeMatchResult: "away",
        homeTeamFullCourtGoalCnt: "2",
        homeTeamId: 51318,
        homeTeamShortName: "阿马多拉",
        matchDate: "2025-04-27",
        matchId: 2146932,
        seasonId: 11974,
        sportteryAwayTeamId: 937,
        sportteryHomeTeamId: 261,
        sportteryMatchId: 0,
        sportteryTournamentId: 0,
        teamMatchResult: "",
        totalTeamFullCourtGoalCnt: 2,
        tournamentId: 140,
        tournamentShortName: "葡超",
        uniformAwayTeamId: 141,
        uniformHomeTeamId: 35076,
        uniformLeagueId: 78,
        winningTeam: "home",
      },
      {
        awayTeamFullCourtGoalCnt: "0",
        awayTeamId: 51318,
        awayTeamShortName: "阿马多拉",
        fullCourtGoal: "2:0",
        gmLeagueId: 55,
        halfTimeGoal: "1:0",
        homeMatchResult: "home",
        homeTeamFullCourtGoalCnt: "2",
        homeTeamId: 1678,
        homeTeamShortName: "波尔图",
        matchDate: "2024-12-17",
        matchId: 2147084,
        seasonId: 11974,
        sportteryAwayTeamId: 261,
        sportteryHomeTeamId: 937,
        sportteryMatchId: 1028773,
        sportteryTournamentId: 55,
        teamMatchResult: "",
        totalTeamFullCourtGoalCnt: 2,
        tournamentId: 140,
        tournamentShortName: "葡超",
        uniformAwayTeamId: 35076,
        uniformHomeTeamId: 141,
        uniformLeagueId: 78,
        winningTeam: "home",
      },
      {
        awayTeamFullCourtGoalCnt: "0",
        awayTeamId: 51318,
        awayTeamShortName: "阿马多拉",
        fullCourtGoal: "2:0",
        gmLeagueId: 0,
        halfTimeGoal: "1:0",
        homeMatchResult: "home",
        homeTeamFullCourtGoalCnt: "2",
        homeTeamId: 1678,
        homeTeamShortName: "波尔图",
        matchDate: "2024-02-18",
        matchId: 1840485,
        seasonId: 9666,
        sportteryAwayTeamId: 261,
        sportteryHomeTeamId: 937,
        sportteryMatchId: 0,
        sportteryTournamentId: 0,
        teamMatchResult: "",
        totalTeamFullCourtGoalCnt: 2,
        tournamentId: 140,
        tournamentShortName: "葡超",
        uniformAwayTeamId: 35076,
        uniformHomeTeamId: 141,
        uniformLeagueId: 78,
        winningTeam: "home",
      },
      {
        awayTeamFullCourtGoalCnt: "1",
        awayTeamId: 1678,
        awayTeamShortName: "波尔图",
        fullCourtGoal: "0:1",
        gmLeagueId: 0,
        halfTimeGoal: "0:1",
        homeMatchResult: "home",
        homeTeamFullCourtGoalCnt: "0",
        homeTeamId: 51318,
        homeTeamShortName: "阿马多拉",
        matchDate: "2023-09-16",
        matchId: 1840416,
        seasonId: 9666,
        sportteryAwayTeamId: 937,
        sportteryHomeTeamId: 261,
        sportteryMatchId: 0,
        sportteryTournamentId: 0,
        teamMatchResult: "",
        totalTeamFullCourtGoalCnt: 1,
        tournamentId: 140,
        tournamentShortName: "葡超",
        uniformAwayTeamId: 141,
        uniformHomeTeamId: 35076,
        uniformLeagueId: 78,
        winningTeam: "away",
      },
      {
        awayTeamFullCourtGoalCnt: "3",
        awayTeamId: 51318,
        awayTeamShortName: "阿马多拉",
        fullCourtGoal: "3:3",
        gmLeagueId: 0,
        halfTimeGoal: "-:-",
        homeMatchResult: "draw",
        homeTeamFullCourtGoalCnt: "3",
        homeTeamId: 1678,
        homeTeamShortName: "波尔图",
        matchDate: "2023-07-26",
        matchId: 1975023,
        seasonId: 10656,
        sportteryAwayTeamId: 261,
        sportteryHomeTeamId: 937,
        sportteryMatchId: 0,
        sportteryTournamentId: 0,
        teamMatchResult: "",
        totalTeamFullCourtGoalCnt: 6,
        tournamentId: 1014,
        tournamentShortName: "俱乐部赛",
        uniformAwayTeamId: 35076,
        uniformHomeTeamId: 141,
        uniformLeagueId: 719,
        winningTeam: "draw",
      },
    ],
    statistics: {
      drawMatchCnt: 1,
      drawProbability: "20%",
      goalCnt: 0,
      lossGoalCnt: 0,
      lossGoalMatchCnt: 1,
      lossProbability: "20%",
      netGoal: 0,
      sportteryTeamId: 0,
      teamId: 0,
      teamShortName: "波尔图",
      totalLegCnt: 5,
      winGoalMatchCnt: 3,
      winProbability: "60%",
    },
  },
  MatchTables: {
    awayTables: {
      total: {
        drawMatchCnt: 5,
        gmTeamId: 261,
        goalCnt: 17,
        groupId: 0,
        groupName: "",
        lossGoalCnt: 22,
        lossGoalMatchCnt: 6,
        netGoal: -5,
        phaseName: "Regular Season",
        points: "14",
        ranking: "14",
        teamShortName: "阿马多拉",
        totalLegCnt: 14,
        uniformTeamId: 0,
        wbsjTeamId: 51318,
        winGoalMatchCnt: 3,
        winProbability: "21%",
      },
      away: {
        drawMatchCnt: 3,
        gmTeamId: 261,
        goalCnt: 7,
        groupId: 0,
        groupName: "",
        lossGoalCnt: 13,
        lossGoalMatchCnt: 3,
        netGoal: -6,
        phaseName: "Regular Season",
        points: "6",
        ranking: "14",
        teamShortName: "阿马多拉",
        totalLegCnt: 7,
        uniformTeamId: 35076,
        wbsjTeamId: 51318,
        winGoalMatchCnt: 1,
        winProbability: "14%",
      },
      home: {
        drawMatchCnt: 2,
        gmTeamId: 261,
        goalCnt: 10,
        groupId: 0,
        groupName: "",
        lossGoalCnt: 9,
        lossGoalMatchCnt: 3,
        netGoal: 1,
        phaseName: "Regular Season",
        points: "8",
        ranking: "12",
        teamShortName: "阿马多拉",
        totalLegCnt: 7,
        uniformTeamId: 141,
        wbsjTeamId: 51318,
        winGoalMatchCnt: 2,
        winProbability: "29%",
      },
    },
    gmLeagueId: 55,
    homeTables: {
      total: {
        drawMatchCnt: 1,
        gmTeamId: 937,
        goalCnt: 30,
        groupId: 0,
        groupName: "",
        lossGoalCnt: 4,
        lossGoalMatchCnt: 0,
        netGoal: 26,
        phaseName: "Regular Season",
        points: "40",
        ranking: "1",
        teamShortName: "波尔图",
        totalLegCnt: 14,
        uniformTeamId: 0,
        wbsjTeamId: 1678,
        winGoalMatchCnt: 13,
        winProbability: "93%",
      },
      away: {
        drawMatchCnt: 0,
        gmTeamId: 937,
        goalCnt: 16,
        groupId: 0,
        groupName: "",
        lossGoalCnt: 2,
        lossGoalMatchCnt: 0,
        netGoal: 14,
        phaseName: "Regular Season",
        points: "21",
        ranking: "1",
        teamShortName: "波尔图",
        totalLegCnt: 7,
        uniformTeamId: 35076,
        wbsjTeamId: 1678,
        winGoalMatchCnt: 7,
        winProbability: "100%",
      },
      home: {
        drawMatchCnt: 1,
        gmTeamId: 937,
        goalCnt: 14,
        groupId: 0,
        groupName: "",
        lossGoalCnt: 2,
        lossGoalMatchCnt: 0,
        netGoal: 12,
        phaseName: "Regular Season",
        points: "19",
        ranking: "1",
        teamShortName: "波尔图",
        totalLegCnt: 7,
        uniformTeamId: 141,
        wbsjTeamId: 1678,
        winGoalMatchCnt: 6,
        winProbability: "86%",
      },
    },
    leagueShortName: "葡超",
    phaseId: 47981,
    seasonId: 13480,
    seasonName: "2025/2026",
    tournamentId: 140,
    uniformLeagueId: 78,
    uniformMatchId: 2334340,
  },
  MatchResult: {
    away: {
      matchList: [
        {
          awayTeamFullCourtGoalCnt: "1",
          awayTeamId: 1498,
          awayTeamShortName: "阿罗卡",
          fullCourtGoal: "3:1",
          halfTimeGoal: "2:0",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "3",
          homeTeamId: 261,
          homeTeamShortName: "阿马多拉",
          matchDate: "2025-12-08",
          matchId: 2367544,
          seasonId: 13480,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 2035826,
          sportteryTournamentId: 55,
          teamMatchResult: "home",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 140,
          tournamentShortName: "葡超",
          uniformAwayTeamId: 1510,
          uniformHomeTeamId: 35076,
          uniformLeagueId: 78,
          winningTeam: "home",
        },
        {
          awayTeamFullCourtGoalCnt: "0",
          awayTeamId: 261,
          awayTeamShortName: "阿马多拉",
          fullCourtGoal: "4:0",
          halfTimeGoal: "3:0",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "4",
          homeTeamId: 1060,
          homeTeamShortName: "里斯本",
          matchDate: "2025-12-01",
          matchId: 2367553,
          seasonId: 13480,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 2035598,
          sportteryTournamentId: 55,
          teamMatchResult: "away",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 140,
          tournamentShortName: "葡超",
          uniformAwayTeamId: 35076,
          uniformHomeTeamId: 140,
          uniformLeagueId: 78,
          winningTeam: "home",
        },
        {
          awayTeamFullCourtGoalCnt: "2",
          awayTeamId: 261,
          awayTeamShortName: "阿马多拉",
          fullCourtGoal: "2:2",
          halfTimeGoal: "",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "2",
          homeTeamId: 40,
          homeTeamShortName: "巴利亚多",
          matchDate: "2025-11-20",
          matchId: 2460672,
          seasonId: 12808,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 0,
          sportteryTournamentId: 0,
          teamMatchResult: "draw",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 1014,
          tournamentShortName: "俱乐部赛",
          uniformAwayTeamId: 35076,
          uniformHomeTeamId: 204,
          uniformLeagueId: 719,
          winningTeam: "draw",
        },
        {
          awayTeamFullCourtGoalCnt: "1",
          awayTeamId: 875,
          awayTeamShortName: "葡国民",
          fullCourtGoal: "1:1",
          halfTimeGoal: "0:1",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "1",
          homeTeamId: 261,
          homeTeamShortName: "阿马多拉",
          matchDate: "2025-11-09",
          matchId: 2367562,
          seasonId: 13480,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 0,
          sportteryTournamentId: 0,
          teamMatchResult: "draw",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 140,
          tournamentShortName: "葡超",
          uniformAwayTeamId: 1203,
          uniformHomeTeamId: 35076,
          uniformLeagueId: 78,
          winningTeam: "draw",
        },
        {
          awayTeamFullCourtGoalCnt: "5",
          awayTeamId: 261,
          awayTeamShortName: "阿马多拉",
          fullCourtGoal: "3:5",
          halfTimeGoal: "1:2",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "3",
          homeTeamId: 2702,
          homeTeamShortName: "卡萨皮亚",
          matchDate: "2025-11-02",
          matchId: 2367569,
          seasonId: 13480,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 0,
          sportteryTournamentId: 0,
          teamMatchResult: "home",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 140,
          tournamentShortName: "葡超",
          uniformAwayTeamId: 35076,
          uniformHomeTeamId: 51219,
          uniformLeagueId: 78,
          winningTeam: "",
        },
        {
          awayTeamFullCourtGoalCnt: "2",
          awayTeamId: 1047,
          awayTeamShortName: "里奥阿维",
          fullCourtGoal: "1:2",
          halfTimeGoal: "1:0",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "1",
          homeTeamId: 261,
          homeTeamShortName: "阿马多拉",
          matchDate: "2025-10-26",
          matchId: 2367576,
          seasonId: 13480,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 0,
          sportteryTournamentId: 0,
          teamMatchResult: "away",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 140,
          tournamentShortName: "葡超",
          uniformAwayTeamId: 455,
          uniformHomeTeamId: 35076,
          uniformLeagueId: 78,
          winningTeam: "",
        },
        {
          awayTeamFullCourtGoalCnt: "1",
          awayTeamId: 261,
          awayTeamShortName: "阿马多拉",
          fullCourtGoal: "3:1",
          halfTimeGoal: "1:1",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "3",
          homeTeamId: 0,
          homeTeamShortName: "Alpendorada",
          matchDate: "2025-10-18",
          matchId: 2449499,
          seasonId: 13780,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 0,
          sportteryTournamentId: 0,
          teamMatchResult: "away",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 570,
          tournamentShortName: "葡萄牙杯",
          uniformAwayTeamId: 35076,
          uniformHomeTeamId: 8459,
          uniformLeagueId: 98,
          winningTeam: "home",
        },
        {
          awayTeamFullCourtGoalCnt: "0",
          awayTeamId: 261,
          awayTeamShortName: "阿马多拉",
          fullCourtGoal: "2:0",
          halfTimeGoal: "2:0",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "2",
          homeTeamId: 393,
          homeTeamShortName: "吉维森特",
          matchDate: "2025-10-04",
          matchId: 2367580,
          seasonId: 13480,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 0,
          sportteryTournamentId: 0,
          teamMatchResult: "away",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 140,
          tournamentShortName: "葡超",
          uniformAwayTeamId: 35076,
          uniformHomeTeamId: 512,
          uniformLeagueId: 78,
          winningTeam: "home",
        },
        {
          awayTeamFullCourtGoalCnt: "0",
          awayTeamId: 1040921,
          awayTeamShortName: "阿维SAD",
          fullCourtGoal: "3:0",
          halfTimeGoal: "3:0",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "3",
          homeTeamId: 261,
          homeTeamShortName: "阿马多拉",
          matchDate: "2025-09-28",
          matchId: 2367586,
          seasonId: 13480,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 0,
          sportteryTournamentId: 0,
          teamMatchResult: "home",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 140,
          tournamentShortName: "葡超",
          uniformAwayTeamId: 35111,
          uniformHomeTeamId: 35076,
          uniformLeagueId: 78,
          winningTeam: "home",
        },
        {
          awayTeamFullCourtGoalCnt: "0",
          awayTeamId: 261,
          awayTeamShortName: "阿马多拉",
          fullCourtGoal: "0:0",
          halfTimeGoal: "0:0",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "0",
          homeTeamId: 1873,
          homeTeamShortName: "通德拉",
          matchDate: "2025-09-21",
          matchId: 2367595,
          seasonId: 13480,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 0,
          sportteryTournamentId: 0,
          teamMatchResult: "draw",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 140,
          tournamentShortName: "葡超",
          uniformAwayTeamId: 35076,
          uniformHomeTeamId: 394,
          uniformLeagueId: 78,
          winningTeam: "draw",
        },
      ],
      statistics: {
        drawMatchCnt: 3,
        drawProbability: "30%",
        goalCnt: 16,
        lossGoalCnt: 18,
        lossGoalMatchCnt: 4,
        lossProbability: "40%",
        netGoal: -2,
        sportteryTeamId: 0,
        teamId: 261,
        teamShortName: "阿马多拉",
        totalLegCnt: 10,
        uniformTeamId: 35076,
        winGoalMatchCnt: 3,
        winProbability: "30%",
      },
    },
    home: {
      matchList: [
        {
          awayTeamFullCourtGoalCnt: "1",
          awayTeamId: 606,
          awayTeamShortName: "马尔默",
          fullCourtGoal: "2:1",
          halfTimeGoal: "2:0",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "2",
          homeTeamId: 937,
          homeTeamShortName: "波尔图",
          matchDate: "2025-12-12",
          matchId: 2439477,
          seasonId: 13334,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 2035928,
          sportteryTournamentId: 70,
          teamMatchResult: "home",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 1103,
          tournamentShortName: "欧罗巴",
          uniformAwayTeamId: 434,
          uniformHomeTeamId: 141,
          uniformLeagueId: 23,
          winningTeam: "home",
        },
        {
          awayTeamFullCourtGoalCnt: "2",
          awayTeamId: 937,
          awayTeamShortName: "波尔图",
          fullCourtGoal: "0:2",
          halfTimeGoal: "0:0",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "0",
          homeTeamId: 1873,
          homeTeamShortName: "通德拉",
          matchDate: "2025-12-08",
          matchId: 2367543,
          seasonId: 13480,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 2035832,
          sportteryTournamentId: 55,
          teamMatchResult: "home",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 140,
          tournamentShortName: "葡超",
          uniformAwayTeamId: 141,
          uniformHomeTeamId: 394,
          uniformLeagueId: 78,
          winningTeam: "",
        },
        {
          awayTeamFullCourtGoalCnt: "3",
          awayTeamId: 538,
          awayTeamShortName: "吉马良斯",
          fullCourtGoal: "1:3",
          halfTimeGoal: "1:1",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "1",
          homeTeamId: 937,
          homeTeamShortName: "波尔图",
          matchDate: "2025-12-05",
          matchId: 2349705,
          seasonId: 13387,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 0,
          sportteryTournamentId: 0,
          teamMatchResult: "away",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 586,
          tournamentShortName: "葡联赛杯",
          uniformAwayTeamId: 300,
          uniformHomeTeamId: 141,
          uniformLeagueId: 44,
          winningTeam: "",
        },
        {
          awayTeamFullCourtGoalCnt: "0",
          awayTeamId: 273,
          awayTeamShortName: "埃斯托里",
          fullCourtGoal: "1:0",
          halfTimeGoal: "1:0",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "1",
          homeTeamId: 937,
          homeTeamShortName: "波尔图",
          matchDate: "2025-12-01",
          matchId: 2367554,
          seasonId: 13480,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 2035605,
          sportteryTournamentId: 55,
          teamMatchResult: "home",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 140,
          tournamentShortName: "葡超",
          uniformAwayTeamId: 665,
          uniformHomeTeamId: 141,
          uniformLeagueId: 78,
          winningTeam: "home",
        },
        {
          awayTeamFullCourtGoalCnt: "0",
          awayTeamId: 186,
          awayTeamShortName: "尼斯",
          fullCourtGoal: "3:0",
          halfTimeGoal: "2:0",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "3",
          homeTeamId: 937,
          homeTeamShortName: "波尔图",
          matchDate: "2025-11-28",
          matchId: 2439360,
          seasonId: 13334,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 2035416,
          sportteryTournamentId: 70,
          teamMatchResult: "home",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 1103,
          tournamentShortName: "欧罗巴",
          uniformAwayTeamId: 276,
          uniformHomeTeamId: 141,
          uniformLeagueId: 23,
          winningTeam: "home",
        },
        {
          awayTeamFullCourtGoalCnt: "0",
          awayTeamId: 0,
          awayTeamShortName: "辛特伦斯",
          fullCourtGoal: "3:0",
          halfTimeGoal: "1:0",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "3",
          homeTeamId: 937,
          homeTeamShortName: "波尔图",
          matchDate: "2025-11-23",
          matchId: 2454866,
          seasonId: 13780,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 0,
          sportteryTournamentId: 0,
          teamMatchResult: "home",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 570,
          tournamentShortName: "葡萄牙杯",
          uniformAwayTeamId: 40638,
          uniformHomeTeamId: 141,
          uniformLeagueId: 98,
          winningTeam: "home",
        },
        {
          awayTeamFullCourtGoalCnt: "1",
          awayTeamId: 937,
          awayTeamShortName: "波尔图",
          fullCourtGoal: "0:1",
          halfTimeGoal: "0:1",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "0",
          homeTeamId: 2111,
          homeTeamShortName: "法马利康",
          matchDate: "2025-11-10",
          matchId: 2367560,
          seasonId: 13480,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 2034953,
          sportteryTournamentId: 55,
          teamMatchResult: "home",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 140,
          tournamentShortName: "葡超",
          uniformAwayTeamId: 141,
          uniformHomeTeamId: 240,
          uniformLeagueId: 78,
          winningTeam: "",
        },
        {
          awayTeamFullCourtGoalCnt: "1",
          awayTeamId: 937,
          awayTeamShortName: "波尔图",
          fullCourtGoal: "1:1",
          halfTimeGoal: "0:0",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "1",
          homeTeamId: 255,
          homeTeamShortName: "乌德勒支",
          matchDate: "2025-11-07",
          matchId: 2439377,
          seasonId: 13334,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 2034789,
          sportteryTournamentId: 70,
          teamMatchResult: "draw",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 1103,
          tournamentShortName: "欧罗巴",
          uniformAwayTeamId: 141,
          uniformHomeTeamId: 190,
          uniformLeagueId: 23,
          winningTeam: "draw",
        },
        {
          awayTeamFullCourtGoalCnt: "1",
          awayTeamId: 269,
          awayTeamShortName: "布拉加",
          fullCourtGoal: "2:1",
          halfTimeGoal: "1:0",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "2",
          homeTeamId: 937,
          homeTeamShortName: "波尔图",
          matchDate: "2025-11-03",
          matchId: 2367996,
          seasonId: 13480,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 2034677,
          sportteryTournamentId: 55,
          teamMatchResult: "home",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 140,
          tournamentShortName: "葡超",
          uniformAwayTeamId: 513,
          uniformHomeTeamId: 141,
          uniformLeagueId: 78,
          winningTeam: "home",
        },
        {
          awayTeamFullCourtGoalCnt: "2",
          awayTeamId: 937,
          awayTeamShortName: "波尔图",
          fullCourtGoal: "1:2",
          halfTimeGoal: "1:1",
          homeMatchResult: "",
          homeTeamFullCourtGoalCnt: "1",
          homeTeamId: 874,
          homeTeamShortName: "摩雷伦斯",
          matchDate: "2025-10-28",
          matchId: 2367573,
          seasonId: 13480,
          sportteryAwayTeamId: 0,
          sportteryHomeTeamId: 0,
          sportteryMatchId: 2034423,
          sportteryTournamentId: 55,
          teamMatchResult: "home",
          totalTeamFullCourtGoalCnt: 0,
          tournamentId: 140,
          tournamentShortName: "葡超",
          uniformAwayTeamId: 141,
          uniformHomeTeamId: 456,
          uniformLeagueId: 78,
          winningTeam: "",
        },
      ],
      statistics: {
        drawMatchCnt: 1,
        drawProbability: "10%",
        goalCnt: 18,
        lossGoalCnt: 7,
        lossGoalMatchCnt: 1,
        lossProbability: "10%",
        netGoal: 11,
        sportteryTeamId: 0,
        teamId: 937,
        teamShortName: "波尔图",
        totalLegCnt: 10,
        uniformTeamId: 141,
        winGoalMatchCnt: 8,
        winProbability: "80%",
      },
    },
  },
  MatchPlayer: {
    away: {
      playerList: [
        {
          appearanceCnt: 14,
          assistAvgCnt: "0.2",
          assistCnt: 3,
          assistProbability: "23%",
          goalAvgCnt: "0.4",
          goalCnt: 5,
          goalProbability: "29%",
          injuryFlag: 0,
          personId: 628502,
          personName: "S. Lopes Cabral",
          playerPositionCode: "Defender",
          playerPositionDesc: "后卫",
          startedMatchCnt: 14,
          substituteMatchCnt: 0,
          suspensionFlag: 0,
          uniformNo: "55",
        },
        {
          appearanceCnt: 13,
          assistAvgCnt: "0.1",
          assistCnt: 1,
          assistProbability: "8%",
          goalAvgCnt: "0.3",
          goalCnt: 4,
          goalProbability: "24%",
          injuryFlag: 0,
          personId: 494156,
          personName: "Kikas",
          playerPositionCode: "Forward",
          playerPositionDesc: "前锋",
          startedMatchCnt: 10,
          substituteMatchCnt: 3,
          suspensionFlag: 0,
          uniformNo: "98",
        },
        {
          appearanceCnt: 13,
          assistAvgCnt: "0.2",
          assistCnt: 2,
          assistProbability: "15%",
          goalAvgCnt: "0.2",
          goalCnt: 2,
          goalProbability: "12%",
          injuryFlag: 0,
          personId: 518999,
          personName: "Ianis Stoica",
          playerPositionCode: "Forward",
          playerPositionDesc: "前锋",
          startedMatchCnt: 6,
          substituteMatchCnt: 7,
          suspensionFlag: 0,
          uniformNo: "10",
        },
      ],
      sportteryTeamId: 261,
      teamId: 51318,
      teamShortName: "阿马多拉",
      uniformTeamId: 35076,
    },
    home: {
      playerList: [
        {
          appearanceCnt: 13,
          assistAvgCnt: "0.1",
          assistCnt: 1,
          assistProbability: "5%",
          goalAvgCnt: "0.7",
          goalCnt: 9,
          goalProbability: "29%",
          injuryFlag: 0,
          personId: 767055,
          personName: "Samu Omorodion",
          playerPositionCode: "Forward",
          playerPositionDesc: "前锋",
          startedMatchCnt: 12,
          substituteMatchCnt: 1,
          suspensionFlag: 0,
          uniformNo: "9",
        },
        {
          appearanceCnt: 11,
          assistAvgCnt: "0",
          assistCnt: 0,
          assistProbability: "0%",
          goalAvgCnt: "0.4",
          goalCnt: 4,
          goalProbability: "13%",
          injuryFlag: 0,
          personId: 833173,
          personName: "William",
          playerPositionCode: "Forward",
          playerPositionDesc: "前锋",
          startedMatchCnt: 6,
          substituteMatchCnt: 5,
          suspensionFlag: 0,
          uniformNo: "7",
        },
        {
          appearanceCnt: 14,
          assistAvgCnt: "0.1",
          assistCnt: 2,
          assistProbability: "10%",
          goalAvgCnt: "0.2",
          goalCnt: 3,
          goalProbability: "10%",
          injuryFlag: 0,
          personId: 585861,
          personName: "博尔哈 塞恩斯",
          playerPositionCode: "Forward",
          playerPositionDesc: "前锋",
          startedMatchCnt: 11,
          substituteMatchCnt: 3,
          suspensionFlag: 0,
          uniformNo: "17",
        },
      ],
      sportteryTeamId: 937,
      teamId: 1678,
      teamShortName: "波尔图",
      uniformTeamId: 141,
    },
    seasonId: 13480,
    seasonName: "2025/2026",
    tournamentId: 140,
    tournamentShortName: "葡超",
    uniformLeagueId: 78,
    uniformMatchId: 2334340,
  },
  InjurySuspension: {
    away: {
      injuriesAndSuspensionsList: [
        {
          appearanceCnt: 6,
          injuryFlag: 1,
          personId: 627653,
          personName: "Alan Godoy",
          playerPositionCode: "Forward",
          playerPositionDesc: "前锋",
          startedMatchCnt: 3,
          substituteMatchCnt: 3,
          suspensionFlag: 0,
          uniformNo: "13",
        },
        {
          appearanceCnt: 0,
          injuryFlag: 1,
          personId: 629062,
          personName: "A. Ndiaye",
          playerPositionCode: "Midfielder",
          playerPositionDesc: "中场",
          startedMatchCnt: 0,
          substituteMatchCnt: 0,
          suspensionFlag: 0,
          uniformNo: "6",
        },
      ],
      sportteryTeamId: 261,
      teamId: 51318,
      teamShortName: "阿马多拉",
      uniformTeamId: 35076,
    },
    home: {
      injuriesAndSuspensionsList: [
        {
          appearanceCnt: 0,
          injuryFlag: 1,
          personId: 270005,
          personName: "M. Grujić",
          playerPositionCode: "Midfielder",
          playerPositionDesc: "中场",
          startedMatchCnt: 0,
          substituteMatchCnt: 0,
          suspensionFlag: 0,
          uniformNo: "16",
        },
        {
          appearanceCnt: 2,
          injuryFlag: 1,
          personId: 430364,
          personName: "Zé Pedro",
          playerPositionCode: "Defender",
          playerPositionDesc: "后卫",
          startedMatchCnt: 0,
          substituteMatchCnt: 2,
          suspensionFlag: 0,
          uniformNo: "3",
        },
        {
          appearanceCnt: 0,
          injuryFlag: 1,
          personId: 460207,
          personName: "André Franco",
          playerPositionCode: "Midfielder",
          playerPositionDesc: "中场",
          startedMatchCnt: 0,
          substituteMatchCnt: 0,
          suspensionFlag: 0,
          uniformNo: "",
        },
      ],
      sportteryTeamId: 937,
      teamId: 1678,
      teamShortName: "波尔图",
      uniformTeamId: 141,
    },
  },
  matchInfoList: [
    {
      businessDate: "2026-04-08",
      subMatchList: [
        {
          awayTeamAbbName: "曼谷联",
          awayTeamAllName: "曼谷联",
          awayTeamCode: "",
          awayTeamId: 2465,
          backColor: "002395",
          businessDate: "2026-04-08",
          homeTeamAbbName: "大阪钢巴",
          homeTeamAllName: "大阪钢巴",
          homeTeamCode: "",
          homeTeamId: 549,
          leagueAbbName: "亚冠乙",
          leagueAllName: "亚洲冠军乙级联赛",
          leagueId: "2068445",
          lineNum: "",
          matchDate: "2026-04-08",
          matchId: 2038920,
          matchName: "",
          matchNum: 3001,
          matchNumDate: "260408",
          matchNumStr: "周三001",
          matchStatus: "Selling",
          matchTime: "18:00",
          matchWeek: "",
          oddsList: [
            {
              a: "3.28",
              d: "3.48",
              goalLine: "-1.00",
              goalLineF: "",
              goalLineValue: "",
              h: "1.86",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HHAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAFU",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "CRS",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "TTG",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "8.00",
              d: "5.05",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "1.24",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HHAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAFU",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "CRS",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "TTG",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "1",
          weekday: "周三",
        },
        {
          awayTeamAbbName: "贝蒂斯",
          awayTeamAllName: "皇家贝蒂斯",
          awayTeamCode: "",
          awayTeamId: 505,
          backColor: "CC9933",
          businessDate: "2026-04-08",
          homeTeamAbbName: "布拉加",
          homeTeamAllName: "布拉加",
          homeTeamCode: "",
          homeTeamId: 269,
          leagueAbbName: "欧罗巴",
          leagueAllName: "欧罗巴联赛",
          leagueId: "70",
          lineNum: "",
          matchDate: "2026-04-09",
          matchId: 2038921,
          matchName: "",
          matchNum: 3002,
          matchNumDate: "260408",
          matchNumStr: "周三002",
          matchStatus: "Selling",
          matchTime: "00:45",
          matchWeek: "",
          oddsList: [
            {
              a: "1.45",
              d: "3.90",
              goalLine: "-1.00",
              goalLineF: "",
              goalLineValue: "",
              h: "5.45",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HHAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAFU",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "CRS",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "TTG",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "2.64",
              d: "3.05",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "2.37",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HHAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAFU",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "CRS",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "TTG",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "1",
          weekday: "周三",
        },
        {
          awayTeamAbbName: "新未来SC",
          awayTeamAllName: "新未来SC",
          awayTeamCode: "",
          awayTeamId: 2065842,
          backColor: "2E7D32",
          businessDate: "2026-04-08",
          homeTeamAbbName: "吉达联合",
          homeTeamAllName: "吉达联合",
          homeTeamCode: "",
          homeTeamId: 751,
          leagueAbbName: "沙职",
          leagueAllName: "沙特职业联赛",
          leagueId: "2068446",
          lineNum: "",
          matchDate: "2026-04-09",
          matchId: 2038922,
          matchName: "",
          matchNum: 3003,
          matchNumDate: "260408",
          matchNumStr: "周三003",
          matchStatus: "Selling",
          matchTime: "02:00",
          matchWeek: "",
          oddsList: [
            {
              a: "2.13",
              d: "3.25",
              goalLine: "-1.00",
              goalLineF: "",
              goalLineValue: "",
              h: "2.84",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HHAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAFU",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "CRS",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "TTG",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "4.45",
              d: "3.80",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "1.56",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HHAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAFU",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "CRS",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "TTG",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "1",
          weekday: "周三",
        },
        {
          awayTeamAbbName: "马竞",
          awayTeamAllName: "马德里竞技",
          awayTeamCode: "",
          awayTeamId: 172,
          backColor: "F75000",
          businessDate: "2026-04-08",
          homeTeamAbbName: "巴萨",
          homeTeamAllName: "巴塞罗那",
          homeTeamCode: "",
          homeTeamId: 401,
          leagueAbbName: "欧冠",
          leagueAllName: "欧洲冠军联赛",
          leagueId: "69",
          lineNum: "",
          matchDate: "2026-04-09",
          matchId: 2038923,
          matchName: "",
          matchNum: 3004,
          matchNumDate: "260408",
          matchNumStr: "周三004",
          matchStatus: "Selling",
          matchTime: "03:00",
          matchWeek: "",
          oddsList: [
            {
              a: "2.61",
              d: "3.80",
              goalLine: "-1.00",
              goalLineF: "",
              goalLineValue: "",
              h: "2.07",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HHAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAFU",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "CRS",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "TTG",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "5.45",
              d: "4.90",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "1.35",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HHAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAFU",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "CRS",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "TTG",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "1",
          weekday: "周三",
        },
        {
          awayTeamAbbName: "利物浦",
          awayTeamAllName: "利物浦",
          awayTeamCode: "",
          awayTeamId: 11,
          backColor: "F75000",
          businessDate: "2026-04-08",
          homeTeamAbbName: "巴黎圣曼",
          homeTeamAllName: "巴黎圣日尔曼",
          homeTeamCode: "",
          homeTeamId: 187,
          leagueAbbName: "欧冠",
          leagueAllName: "欧洲冠军联赛",
          leagueId: "69",
          lineNum: "",
          matchDate: "2026-04-09",
          matchId: 2038924,
          matchName: "",
          matchNum: 3005,
          matchNumDate: "260408",
          matchNumStr: "周三005",
          matchStatus: "Selling",
          matchTime: "03:00",
          matchWeek: "",
          oddsList: [
            {
              a: "2.04",
              d: "3.90",
              goalLine: "-1.00",
              goalLineF: "",
              goalLineValue: "",
              h: "2.62",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HHAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAFU",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "CRS",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "TTG",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "4.00",
              d: "3.95",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "1.60",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HHAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAFU",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "CRS",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "TTG",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "1",
          weekday: "周三",
        },
        {
          awayTeamAbbName: "弗拉门戈",
          awayTeamAllName: "弗拉门戈",
          awayTeamCode: "",
          awayTeamId: 571,
          backColor: "00A653",
          businessDate: "2026-04-08",
          homeTeamAbbName: "库斯科",
          homeTeamAllName: "库斯科",
          homeTeamCode: "",
          homeTeamId: 1776,
          leagueAbbName: "解放者杯",
          leagueAllName: "南美解放者杯",
          leagueId: "49",
          lineNum: "",
          matchDate: "2026-04-09",
          matchId: 2038925,
          matchName: "",
          matchNum: 3006,
          matchNumDate: "260408",
          matchNumStr: "周三006",
          matchStatus: "Selling",
          matchTime: "08:30",
          matchWeek: "",
          oddsList: [
            {
              a: "3.26",
              d: "3.25",
              goalLine: "+1.00",
              goalLineF: "",
              goalLineValue: "",
              h: "1.94",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HHAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAFU",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "CRS",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "TTG",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "1.67",
              d: "3.40",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "4.25",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HHAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAFU",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "CRS",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "TTG",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "1",
          weekday: "周三",
        },
        {
          awayTeamAbbName: "帕梅拉斯",
          awayTeamAllName: "帕尔梅拉斯",
          awayTeamCode: "",
          awayTeamId: 577,
          backColor: "00A653",
          businessDate: "2026-04-08",
          homeTeamAbbName: "巴兰基亚",
          homeTeamAllName: "巴兰基亚青年",
          homeTeamCode: "",
          homeTeamId: 632,
          leagueAbbName: "解放者杯",
          leagueAllName: "南美解放者杯",
          leagueId: "49",
          lineNum: "",
          matchDate: "2026-04-09",
          matchId: 2038926,
          matchName: "",
          matchNum: 3007,
          matchNumDate: "260408",
          matchNumStr: "周三007",
          matchStatus: "Selling",
          matchTime: "08:30",
          matchWeek: "",
          oddsList: [
            {
              a: "3.00",
              d: "3.35",
              goalLine: "+1.00",
              goalLineF: "",
              goalLineValue: "",
              h: "2.01",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HHAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAFU",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "CRS",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "TTG",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "1.61",
              d: "3.40",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "4.68",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HHAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAFU",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "CRS",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "TTG",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "1",
          weekday: "周三",
        },
      ],
      weekday: "周三",
      matchCount: 7,
      matchNumDate: "260408",
    },
    {
      businessDate: "2026-04-09",
      subMatchList: [
        {
          awayTeamAbbName: "胡巴卡德",
          awayTeamAllName: "胡巴尔卡德西亚",
          awayTeamCode: "",
          awayTeamId: 2065838,
          backColor: "2E7D32",
          businessDate: "2026-04-09",
          homeTeamAbbName: "达马克",
          homeTeamAllName: "达马克",
          homeTeamCode: "",
          homeTeamId: 2065841,
          leagueAbbName: "沙职",
          leagueAllName: "沙特职业联赛",
          leagueId: "2068446",
          lineNum: "",
          matchDate: "2026-04-10",
          matchId: 2038927,
          matchName: "",
          matchNum: 4001,
          matchNumDate: "260409",
          matchNumStr: "周四001",
          matchStatus: "Selling",
          matchTime: "00:00",
          matchWeek: "",
          oddsList: [
            {
              a: "1.91",
              d: "3.68",
              goalLine: "+1.00",
              goalLineF: "",
              goalLineValue: "",
              h: "3.00",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HHAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAFU",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "CRS",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "TTG",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "1.27",
              d: "4.95",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "7.12",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HHAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAFU",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "CRS",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "TTG",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "1",
          weekday: "周四",
        },
        {
          awayTeamAbbName: "雅典AEK",
          awayTeamAllName: "雅典AEK",
          awayTeamCode: "",
          awayTeamId: 277,
          backColor: "23ad2b",
          businessDate: "2026-04-09",
          homeTeamAbbName: "巴列卡诺",
          homeTeamAllName: "巴列卡诺",
          homeTeamCode: "",
          homeTeamId: 849,
          leagueAbbName: "欧协联",
          leagueAllName: "欧洲协会联赛",
          leagueId: "1033103",
          lineNum: "",
          matchDate: "2026-04-10",
          matchId: 2038928,
          matchName: "",
          matchNum: 4002,
          matchNumDate: "260409",
          matchNumStr: "周四002",
          matchStatus: "Define",
          matchTime: "00:45",
          matchWeek: "",
          oddsList: [
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 0,
              cbtSingle: 0,
              cbtValue: 0,
              intAllUp: 0,
              intSingle: 0,
              intValue: 0,
              poolCode: "",
              poolPrimaryId: 0,
              poolStatus: "",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "",
          weekday: "周四",
        },
        {
          awayTeamAbbName: "塞尔塔",
          awayTeamAllName: "维戈塞尔塔",
          awayTeamCode: "",
          awayTeamId: 508,
          backColor: "CC9933",
          businessDate: "2026-04-09",
          homeTeamAbbName: "弗赖堡",
          homeTeamAllName: "弗赖堡",
          homeTeamCode: "",
          homeTeamId: 141,
          leagueAbbName: "欧罗巴",
          leagueAllName: "欧罗巴联赛",
          leagueId: "70",
          lineNum: "",
          matchDate: "2026-04-10",
          matchId: 2038929,
          matchName: "",
          matchNum: 4003,
          matchNumDate: "260409",
          matchNumStr: "周四003",
          matchStatus: "Selling",
          matchTime: "03:00",
          matchWeek: "",
          oddsList: [
            {
              a: "1.59",
              d: "3.60",
              goalLine: "-1.00",
              goalLineF: "",
              goalLineValue: "",
              h: "4.50",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HHAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAFU",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "CRS",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "TTG",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "3.10",
              d: "3.10",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "2.07",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HHAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAFU",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "CRS",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "TTG",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "1",
          weekday: "周四",
        },
        {
          awayTeamAbbName: "诺丁汉",
          awayTeamAllName: "诺丁汉森林",
          awayTeamCode: "",
          awayTeamId: 52,
          backColor: "CC9933",
          businessDate: "2026-04-09",
          homeTeamAbbName: "波尔图",
          homeTeamAllName: "波尔图",
          homeTeamCode: "",
          homeTeamId: 937,
          leagueAbbName: "欧罗巴",
          leagueAllName: "欧罗巴联赛",
          leagueId: "70",
          lineNum: "",
          matchDate: "2026-04-10",
          matchId: 2038930,
          matchName: "",
          matchNum: 4004,
          matchNumDate: "260409",
          matchNumStr: "周四004",
          matchStatus: "Selling",
          matchTime: "03:00",
          matchWeek: "",
          oddsList: [
            {
              a: "1.74",
              d: "3.45",
              goalLine: "-1.00",
              goalLineF: "",
              goalLineValue: "",
              h: "3.78",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HHAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAFU",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "CRS",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "TTG",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "3.70",
              d: "3.20",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "1.83",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HHAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAFU",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "CRS",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "TTG",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "1",
          weekday: "周四",
        },
        {
          awayTeamAbbName: "维拉",
          awayTeamAllName: "阿斯顿维拉",
          awayTeamCode: "",
          awayTeamId: 2,
          backColor: "CC9933",
          businessDate: "2026-04-09",
          homeTeamAbbName: "博洛尼亚",
          homeTeamAllName: "博洛尼亚",
          homeTeamCode: "",
          homeTeamId: 118,
          leagueAbbName: "欧罗巴",
          leagueAllName: "欧罗巴联赛",
          leagueId: "70",
          lineNum: "",
          matchDate: "2026-04-10",
          matchId: 2038931,
          matchName: "",
          matchNum: 4005,
          matchNumDate: "260409",
          matchNumStr: "周四005",
          matchStatus: "Selling",
          matchTime: "03:00",
          matchWeek: "",
          oddsList: [
            {
              a: "4.70",
              d: "3.70",
              goalLine: "+1.00",
              goalLineF: "",
              goalLineValue: "",
              h: "1.55",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HHAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAFU",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "CRS",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "TTG",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "2.15",
              d: "3.13",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "2.90",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HHAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAFU",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "CRS",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "TTG",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "1",
          weekday: "周四",
        },
        {
          awayTeamAbbName: "佛罗伦萨",
          awayTeamAllName: "佛罗伦萨",
          awayTeamCode: "",
          awayTeamId: 122,
          backColor: "23ad2b",
          businessDate: "2026-04-09",
          homeTeamAbbName: "水晶宫",
          homeTeamAllName: "水晶宫",
          homeTeamCode: "",
          homeTeamId: 8,
          leagueAbbName: "欧协联",
          leagueAllName: "欧洲协会联赛",
          leagueId: "1033103",
          lineNum: "",
          matchDate: "2026-04-10",
          matchId: 2038932,
          matchName: "",
          matchNum: 4006,
          matchNumDate: "260409",
          matchNumStr: "周四006",
          matchStatus: "Define",
          matchTime: "03:00",
          matchWeek: "",
          oddsList: [
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 0,
              cbtSingle: 0,
              cbtValue: 0,
              intAllUp: 0,
              intSingle: 0,
              intValue: 0,
              poolCode: "",
              poolPrimaryId: 0,
              poolStatus: "",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "",
          weekday: "周四",
        },
        {
          awayTeamAbbName: "斯特拉斯",
          awayTeamAllName: "斯特拉斯堡",
          awayTeamCode: "",
          awayTeamId: 191,
          backColor: "23ad2b",
          businessDate: "2026-04-09",
          homeTeamAbbName: "美因茨",
          homeTeamAllName: "美因茨",
          homeTeamCode: "",
          homeTeamId: 147,
          leagueAbbName: "欧协联",
          leagueAllName: "欧洲协会联赛",
          leagueId: "1033103",
          lineNum: "",
          matchDate: "2026-04-10",
          matchId: 2038933,
          matchName: "",
          matchNum: 4007,
          matchNumDate: "260409",
          matchNumStr: "周四007",
          matchStatus: "Define",
          matchTime: "03:00",
          matchWeek: "",
          oddsList: [
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 0,
              cbtSingle: 0,
              cbtValue: 0,
              intAllUp: 0,
              intSingle: 0,
              intValue: 0,
              poolCode: "",
              poolPrimaryId: 0,
              poolStatus: "",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "",
          weekday: "周四",
        },
        {
          awayTeamAbbName: "科林蒂安",
          awayTeamAllName: "科林蒂安",
          awayTeamCode: "",
          awayTeamId: 567,
          backColor: "00A653",
          businessDate: "2026-04-09",
          homeTeamAbbName: "普拉滕斯",
          homeTeamAllName: "普拉滕斯",
          homeTeamCode: "",
          homeTeamId: 2071701,
          leagueAbbName: "解放者杯",
          leagueAllName: "南美解放者杯",
          leagueId: "49",
          lineNum: "",
          matchDate: "2026-04-10",
          matchId: 2038934,
          matchName: "",
          matchNum: 4008,
          matchNumDate: "260409",
          matchNumStr: "周四008",
          matchStatus: "Selling",
          matchTime: "08:00",
          matchWeek: "",
          oddsList: [
            {
              a: "1.36",
              d: "3.95",
              goalLine: "-1.00",
              goalLineF: "",
              goalLineValue: "",
              h: "7.10",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HHAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAFU",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "CRS",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "",
              d: "",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "TTG",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
            {
              a: "2.70",
              d: "2.62",
              goalLine: "",
              goalLineF: "",
              goalLineValue: "",
              h: "2.65",
              matchId: 0,
              matchNum: 0,
              odds: "",
              poolCode: "HAD",
              poolId: 0,
              updateDate: "",
              updateTime: "",
            },
          ],
          poolList: [
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HHAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAFU",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "CRS",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 1,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "TTG",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
            {
              cbtAllUp: 1,
              cbtSingle: 0,
              cbtValue: 1,
              intAllUp: 0,
              intSingle: 0,
              intValue: 2,
              poolCode: "HAD",
              poolPrimaryId: 0,
              poolStatus: "Selling",
            },
          ],
          poolStatus: "",
          remark: "",
          sellStatus: "1",
          weekday: "周四",
        },
      ],
      weekday: "周四",
      matchCount: 8,
      matchNumDate: "260409",
    },
  ],
};
